#ifndef EVENTS_H_
#define EVENTS_H_

#include "contiki.h"

typedef enum {
    EVENT_FAILURE,
    EVENT_RECOVERY,
    EVENT_LOAD_VARIATION
} event_type_t;

typedef struct {
    clock_time_t time;
    event_type_t event_type;
    int target_send_interval;
    int target_packet_size;
    int node_id;
} node_event_t;

int event_list_size = 120;

node_event_t event_list[] = {
    {.time = 0, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 11, .target_packet_size = 56, .node_id = -1},
    {.time = 30, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 3, .target_packet_size = 77, .node_id = -1},
    {.time = 60, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 67, .node_id = -1},
    {.time = 90, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 71, .node_id = -1},
    {.time = 120, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 63, .node_id = -1},
    {.time = 150, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 11, .target_packet_size = 60, .node_id = -1},
    {.time = 180, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 63, .node_id = -1},
    {.time = 210, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 80, .node_id = -1},
    {.time = 240, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 59, .node_id = -1},
    {.time = 270, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 6, .target_packet_size = 66, .node_id = -1},
    {.time = 300, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 6, .target_packet_size = 68, .node_id = -1},
    {.time = 330, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 73, .node_id = -1},
    {.time = 360, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 68, .node_id = -1},
    {.time = 390, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 50, .node_id = -1},
    {.time = 420, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 69, .node_id = -1},
    {.time = 450, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 6, .target_packet_size = 67, .node_id = -1},
    {.time = 480, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 10, .target_packet_size = 51, .node_id = -1},
    {.time = 510, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 65, .node_id = -1},
    {.time = 540, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 75, .node_id = -1},
    {.time = 570, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 77, .node_id = -1},
    {.time = 600, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 51, .node_id = -1},
    {.time = 630, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 68, .node_id = -1},
    {.time = 660, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 53, .node_id = -1},
    {.time = 690, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 60, .node_id = -1},
    {.time = 720, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 10, .target_packet_size = 53, .node_id = -1},
    {.time = 750, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 50, .node_id = -1},
    {.time = 780, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 11, .target_packet_size = 57, .node_id = -1},
    {.time = 810, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 11, .target_packet_size = 54, .node_id = -1},
    {.time = 840, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 70, .node_id = -1},
    {.time = 870, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 58, .node_id = -1},
    {.time = 900, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 58, .node_id = -1},
    {.time = 930, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 64, .node_id = -1},
    {.time = 960, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 53, .node_id = -1},
    {.time = 990, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 6, .target_packet_size = 67, .node_id = -1},
    {.time = 1020, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 52, .node_id = -1},
    {.time = 1050, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 12, .target_packet_size = 58, .node_id = -1},
    {.time = 1080, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 62, .node_id = -1},
    {.time = 1110, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 6, .target_packet_size = 62, .node_id = -1},
    {.time = 1140, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 77, .node_id = -1},
    {.time = 1170, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 59, .node_id = -1},
    {.time = 1200, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 72, .node_id = -1},
    {.time = 1230, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 10, .target_packet_size = 55, .node_id = -1},
    {.time = 1260, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 80, .node_id = -1},
    {.time = 1290, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 68, .node_id = -1},
    {.time = 1320, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 60, .node_id = -1},
    {.time = 1350, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 69, .node_id = -1},
    {.time = 1380, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 72, .node_id = -1},
    {.time = 1410, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 67, .node_id = -1},
    {.time = 1440, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 62, .node_id = -1},
    {.time = 1470, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 3, .target_packet_size = 72, .node_id = -1},
    {.time = 1500, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 63, .node_id = -1},
    {.time = 1530, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 68, .node_id = -1},
    {.time = 1560, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 56, .node_id = -1},
    {.time = 1590, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 80, .node_id = -1},
    {.time = 1620, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 53, .node_id = -1},
    {.time = 1650, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 10, .target_packet_size = 55, .node_id = -1},
    {.time = 1680, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 10, .target_packet_size = 60, .node_id = -1},
    {.time = 1710, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 12, .target_packet_size = 52, .node_id = -1},
    {.time = 1740, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 63, .node_id = -1},
    {.time = 1770, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 52, .node_id = -1},
    {.time = 1800, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 50, .node_id = -1},
    {.time = 1830, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 12, .target_packet_size = 51, .node_id = -1},
    {.time = 1860, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 72, .node_id = -1},
    {.time = 1890, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 67, .node_id = -1},
    {.time = 1920, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 11, .target_packet_size = 56, .node_id = -1},
    {.time = 1950, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 64, .node_id = -1},
    {.time = 1980, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 69, .node_id = -1},
    {.time = 2010, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 4, .target_packet_size = 79, .node_id = -1},
    {.time = 2040, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 75, .node_id = -1},
    {.time = 2070, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 12, .target_packet_size = 54, .node_id = -1},
    {.time = 2100, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 70, .node_id = -1},
    {.time = 2130, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 10, .target_packet_size = 56, .node_id = -1},
    {.time = 2160, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 71, .node_id = -1},
    {.time = 2190, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 3, .target_packet_size = 80, .node_id = -1},
    {.time = 2220, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 80, .node_id = -1},
    {.time = 2250, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 4, .target_packet_size = 76, .node_id = -1},
    {.time = 2280, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 61, .node_id = -1},
    {.time = 2310, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 12, .target_packet_size = 51, .node_id = -1},
    {.time = 2340, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 3, .target_packet_size = 79, .node_id = -1},
    {.time = 2370, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 63, .node_id = -1},
    {.time = 2400, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 12, .target_packet_size = 55, .node_id = -1},
    {.time = 2430, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 10, .target_packet_size = 54, .node_id = -1},
    {.time = 2460, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 70, .node_id = -1},
    {.time = 2490, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 3, .target_packet_size = 74, .node_id = -1},
    {.time = 2520, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 57, .node_id = -1},
    {.time = 2550, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 71, .node_id = -1},
    {.time = 2580, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 3, .target_packet_size = 70, .node_id = -1},
    {.time = 2610, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 4, .target_packet_size = 73, .node_id = -1},
    {.time = 2640, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 4, .target_packet_size = 76, .node_id = -1},
    {.time = 2670, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 6, .target_packet_size = 64, .node_id = -1},
    {.time = 2700, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 59, .node_id = -1},
    {.time = 2730, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 12, .target_packet_size = 59, .node_id = -1},
    {.time = 2760, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 12, .target_packet_size = 52, .node_id = -1},
    {.time = 2790, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 60, .node_id = -1},
    {.time = 2820, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 51, .node_id = -1},
    {.time = 2850, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 70, .node_id = -1},
    {.time = 2880, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 77, .node_id = -1},
    {.time = 2910, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 12, .target_packet_size = 60, .node_id = -1},
    {.time = 2940, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 63, .node_id = -1},
    {.time = 2970, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 60, .node_id = -1},
    {.time = 3000, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 61, .node_id = -1},
    {.time = 3030, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 61, .node_id = -1},
    {.time = 3060, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 3, .target_packet_size = 72, .node_id = -1},
    {.time = 3090, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 11, .target_packet_size = 50, .node_id = -1},
    {.time = 3120, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 74, .node_id = -1},
    {.time = 3150, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 70, .node_id = -1},
    {.time = 3180, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 73, .node_id = -1},
    {.time = 3210, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 62, .node_id = -1},
    {.time = 3240, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 8, .target_packet_size = 61, .node_id = -1},
    {.time = 3270, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 56, .node_id = -1},
    {.time = 3300, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 62, .node_id = -1},
    {.time = 3330, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 11, .target_packet_size = 56, .node_id = -1},
    {.time = 3360, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 7, .target_packet_size = 63, .node_id = -1},
    {.time = 3390, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 60, .node_id = -1},
    {.time = 3420, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 5, .target_packet_size = 68, .node_id = -1},
    {.time = 3450, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 6, .target_packet_size = 62, .node_id = -1},
    {.time = 3480, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 3, .target_packet_size = 74, .node_id = -1},
    {.time = 3510, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 2, .target_packet_size = 80, .node_id = -1},
    {.time = 3540, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 56, .node_id = -1},
    {.time = 3570, .event_type = EVENT_LOAD_VARIATION, .target_send_interval = 9, .target_packet_size = 50, .node_id = -1},
};

#endif /* EVENTS_H_ */
